server:
  port: 9002

#application name
spring:
  application:
    name: USER-SERVICE

#Eureka client configuration
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost